name: Update metadata.js from CSV

on:
  push:
    paths:
      - 'blog/metadata.csv'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Manually install csv-parser
      run: npm install csv-parser

    - name: Run update.js
      run: node blog/update.js

    - name: Commit and push metadata.js
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add blog/metadata.js
        git diff --cached --quiet || git commit -m "Auto-update metadata.js from metadata.csv"
        git push https://x-access-token:${GH_PAT}@github.com/jaypasnagasai/jaypasnagasai.github.io.git HEAD:main
